[workspace]
members = [
    "spdmlib",
    "codec",
    "test/spdm-requester-emu",
    "test/spdm-responder-emu",


]
exclude = [
    "external/ring",
    "external/webpki",
    "fuzz-target/"
]
